name: local_db
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.1

# Add regular dependencies here.
dependencies:
  sqflite: ^2.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
